language: d
sudo: false
dist: xenial

branches:
  only:
  - master

addons:
  apt:
    packages:
      - pkg-config
      - zlib1g-dev
      - libssl-dev

d:
  - dmd-2.087.1
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1
  - dmd-2.083.1
  - dmd-2.082.1
  - ldc-1.16.0
  - ldc-1.15.0
  - ldc-1.14.0
  - ldc-1.13.0
  - ldc-1.12.0

#before_install:
  #- pyenv global system 3.6
  #- pip3 install meson>=0.40

#install:
  #- mkdir .ntmp
  #- curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  #- unzip .ntmp/ninja-linux.zip -d .ntmp

#before_script:
  #- export PATH=$PATH:$PWD/.ntmp

script:
  - dub build -b release
  - dub test
  - dub build --root examples/htmlgenerator
  - dub build --root examples/htmlserver
  # test building with Meson
  - mkdir build && cd build
  #- meson ..
  #- ninja -j4
  #- DESTDIR=/tmp/diet_inst_target ninja install
